require("dotenv").config();

const express = require("express");
const http = require("http");
const cors = require("cors");
const { Server } = require("socket.io");
const { Pool } = require("pg");

const app = express();

const PORT = process.env.PORT || 3000;
const CLIENT_URL = process.env.CLIENT_URL || "*";
const DATABASE_URL = process.env.DATABASE_URL;

// ----------------------------------------------------
// Middleware
// ----------------------------------------------------

app.use(
  cors({
    origin: CLIENT_URL === "*" ? true : CLIENT_URL,
    credentials: true,
  }),
);

app.use(express.json());

// ----------------------------------------------------
// PostgreSQL
// ----------------------------------------------------

if (!DATABASE_URL) {
  console.warn("WARNING: Falta DATABASE_URL. La API no podrá usar PostgreSQL.");
}

const pool = new Pool({
  connectionString: DATABASE_URL,
  ssl: DATABASE_URL
    ? {
        rejectUnauthorized: false,
      }
    : false,
});

// ----------------------------------------------------
// Inicialización de tablas
// ----------------------------------------------------
async function initDatabase() {
  if (!DATABASE_URL) {
    console.warn("DATABASE_URL no está configurada");
    return;
  }

  await pool.query(`
    CREATE TABLE IF NOT EXISTS chat_messages (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      room TEXT NOT NULL DEFAULT 'general',
      username TEXT NOT NULL DEFAULT 'anonymous',
      text TEXT NOT NULL DEFAULT '',
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
  `);

  await pool.query(`
    ALTER TABLE chat_messages
    ADD COLUMN IF NOT EXISTS room TEXT NOT NULL DEFAULT 'general';
  `);

  await pool.query(`
    ALTER TABLE chat_messages
    ADD COLUMN IF NOT EXISTS username TEXT NOT NULL DEFAULT 'anonymous';
  `);

  await pool.query(`
    ALTER TABLE chat_messages
    ADD COLUMN IF NOT EXISTS text TEXT NOT NULL DEFAULT '';
  `);

  await pool.query(`
    ALTER TABLE chat_messages
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
  `);

  console.log("Database initialized");
}
// ----------------------------------------------------
// API REST
// ----------------------------------------------------

app.get("/", (req, res) => {
  res.json({
    ok: true,
    name: "shopp-server",
    message: "API funcionando",
  });
});

app.get("/api/health", async (req, res) => {
  try {
    let database = "not_configured";

    if (DATABASE_URL) {
      const result = await pool.query("SELECT NOW() AS now");
      database = {
        ok: true,
        now: result.rows[0].now,
      };
    }

    res.json({
      ok: true,
      server: "running",
      database,
    });
  } catch (error) {
    console.error("GET /api/health error:", error);

    res.status(500).json({
      ok: false,
      error: "Database connection failed",
      detail: error.message,
    });
  }
});

app.get("/api/messages", async (req, res) => {
  try {
    const room = req.query.room || "general";

    const result = await pool.query(
      `
      SELECT id, room, username, text, created_at
      FROM chat_messages
      WHERE room = $1
      ORDER BY created_at ASC
      LIMIT 100
      `,
      [room],
    );

    res.json({
      ok: true,
      room,
      messages: result.rows,
    });
  } catch (error) {
    console.error("GET /api/messages error:", error);

    res.status(500).json({
      ok: false,
      error: "Could not fetch messages",
      detail: error.message,
    });
  }
});

app.post("/api/messages", async (req, res) => {
  try {
    const room = req.body.room || "general";
    const username = req.body.username || "anonymous";
    const text = req.body.text;

    if (!text || !text.trim()) {
      return res.status(400).json({
        ok: false,
        error: "text is required",
      });
    }

    const result = await pool.query(
      `
      INSERT INTO chat_messages (room, username, text)
      VALUES ($1, $2, $3)
      RETURNING id, room, username, text, created_at
      `,
      [room, username, text.trim()],
    );

    const message = result.rows[0];

    io.to(room).emit("chat:message", message);

    res.status(201).json({
      ok: true,
      message,
    });
  } catch (error) {
    console.error("POST /api/messages error:", error);

    res.status(500).json({
      ok: false,
      error: "Could not create message",
      detail: error.message,
    });
  }
});

app.delete("/api/messages/:id", async (req, res) => {
  try {
    const id = Number(req.params.id);

    if (!Number.isInteger(id)) {
      return res.status(400).json({
        ok: false,
        error: "Invalid message id",
      });
    }

    const result = await pool.query(
      `
      DELETE FROM chat_messages
      WHERE id = $1
      RETURNING id, room, username, text, created_at
      `,
      [id],
    );

    if (result.rowCount === 0) {
      return res.status(404).json({
        ok: false,
        error: "Message not found",
      });
    }

    res.json({
      ok: true,
      deleted: result.rows[0],
    });
  } catch (error) {
    console.error("DELETE /api/messages/:id error:", error);

    res.status(500).json({
      ok: false,
      error: "Could not delete message",
      detail: error.message,
    });
  }
});

app.post("/api/dev/reset-test-db", async (req, res) => {
  try {
    await pool.query(`
      DROP TABLE IF EXISTS chat_messages;
    `);

    await pool.query(`
      CREATE TABLE chat_messages (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        room TEXT NOT NULL DEFAULT 'general',
        username TEXT NOT NULL DEFAULT 'anonymous',
        text TEXT NOT NULL DEFAULT '',
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `);

    await pool.query(`
      CREATE INDEX IF NOT EXISTS idx_chat_messages_room_created_at
      ON chat_messages (room, created_at DESC);
    `);

    await pool.query(
      `
      INSERT INTO chat_messages (room, username, text)
      VALUES
        ($1, $2, $3),
        ($4, $5, $6),
        ($7, $8, $9),
        ($10, $11, $12)
      `,
      [
        "general",
        "Josh",
        "Mensaje de prueba 1 desde Thunder Client",

        "general",
        "Ana",
        "Mensaje de prueba 2 desde Thunder Client",

        "soporte",
        "Admin",
        "Mensaje de prueba en la sala soporte",

        "shopp",
        "Josh",
        "Probando la sala shopp",
      ],
    );

    const result = await pool.query(`
      SELECT id, room, username, text, created_at
      FROM chat_messages
      ORDER BY id ASC;
    `);

    res.json({
      ok: true,
      message: "Base de datos de prueba creada correctamente",
      count: result.rowCount,
      rows: result.rows,
    });
  } catch (error) {
    console.error("POST /api/dev/reset-test-db error:", error);

    res.status(500).json({
      ok: false,
      error: "Could not reset test database",
      detail: error.message,
    });
  }
});

// ----------------------------------------------------
// Socket.io
// ----------------------------------------------------

const server = http.createServer(app);

const io = new Server(server, {
  cors: {
    origin: CLIENT_URL === "*" ? true : CLIENT_URL,
    methods: ["GET", "POST"],
    credentials: true,
  },
});

io.on("connection", (socket) => {
  console.log("Socket connected:", socket.id);

  socket.on(
    "chat:join",
    ({ room = "general", username = "anonymous" } = {}) => {
      socket.join(room);

      socket.emit("chat:joined", {
        ok: true,
        room,
        username,
      });
    },
  );

  socket.on(
    "chat:message",
    async ({ room = "general", username = "anonymous", text }) => {
      try {
        if (!text || !text.trim()) return;

        const result = await pool.query(
          `
        INSERT INTO chat_messages (room, username, text)
        VALUES ($1, $2, $3)
        RETURNING id, room, username, text, created_at
        `,
          [room, username, text.trim()],
        );

        const message = result.rows[0];

        io.to(room).emit("chat:message", message);
      } catch (error) {
        console.error("socket chat:message error:", error);

        socket.emit("chat:error", {
          ok: false,
          error: "Could not save message",
          detail: error.message,
        });
      }
    },
  );

  socket.on("disconnect", () => {
    console.log("Socket disconnected:", socket.id);
  });
});

// ----------------------------------------------------
// Start
// ----------------------------------------------------

initDatabase()
  .then(() => {
    server.listen(PORT, () => {
      console.log(`Server running on port ${PORT}`);
    });
  })
  .catch((error) => {
    console.error("Database initialization failed:", error);

    server.listen(PORT, () => {
      console.log(`Server running on port ${PORT} without database init`);
    });
  });
