DROP TABLE IF EXISTS chat_messages;

CREATE TABLE chat_messages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room TEXT NOT NULL DEFAULT 'general',
  username TEXT NOT NULL DEFAULT 'anonymous',
  text TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_messages_room_created_at
ON chat_messages (room, created_at DESC);

INSERT INTO chat_messages (room, username, text)
VALUES
  ('general', 'Josh', 'Mensaje de prueba 1 desde PostgreSQL'),
  ('general', 'Ana', 'Mensaje de prueba 2 desde PostgreSQL'),
  ('soporte', 'Admin', 'Mensaje de prueba en la sala soporte'),
  ('shopp', 'Josh', 'Probando la sala shopp con Thunder Client');

SELECT id, room, username, text, created_at
FROM chat_messages
ORDER BY created_at ASC;